### ISSUE TITLE
Upload checkbox images

### ISSUE THREAD

**Issue by pdeubel** [LynnHaDo/Checkbox-Detection#1]
Hi, very nice project! From my understanding you created a synthetic dataset by pasting in images of checkboxes onto documents. Would it be possible to share the images of the checkboxes you used, or if not, could you describe from where you got these images? Thanks in advance

**Comment by pdeubel** [comment]
Many thanks for your fast response. One additional question, could you upload your trained model on HuggingFace?

**Comment by LynnHaDo** [comment]
Actually if you navigate to my HuggingFace Space where I host the demo of this model, in the Files tab, you should be able to see 2 models I uploaded there: one is a classification model, and another is the detection model. 

Feel free to use or fine-tune my models for your specific needs if needed. If you decide to use them in any part of your work, please make sure to cite this repository in either one of the following ways: 

**BibTeX**
@software{Do_Checkbox_Detection_Baseline_2023,
author = {Do, Linh},
license = {MIT},
month = aug,
title = {{Checkbox Detection Baseline Model}},
url = {https://github.com/LynnHaDo/Checkbox-Detection},
year = {2023}
} 

or

**APA**
Do, L. (2023). Checkbox Detection Baseline Model [Computer software]. https://github.com/LynnHaDo/Checkbox-Detection

**Comment by arvisioncode** [comment]
Thank you very much for your work @LynnHaDo !
If you can finally upload the dataset you prepared with the labels, can you let me know in this thread?
