### ISSUE TITLE
Model location

### ISSUE THREAD

**Issue by tommasofavaron1** [LynnHaDo/Checkbox-Detection#2]
Hi,
i cant find the folder for the model.
models/detector-model.pt
models/classifier-model.pt
where can i find them?

**Comment by LynnHaDo** [comment]
Hi!

Sorry for the late reply. You should be able to find it in my HuggingFace space, at this [link](https://huggingface.co/spaces/linhdo/checkbox-detector/tree/main/models). 

Hope this helps!
