### ISSUE TITLE
problem with adjacent boxes

### ISSUE THREAD

**Issue by clogu** [LynnHaDo/Checkbox-Detection#4]
Hello, 
My problem is adjacent boxes. My survey has five boxes in same row bot they are adjacent like in pic. Have you got any solution that? 
![test](https://github.com/LynnHaDo/Checkbox-Detection/assets/10337986/c38af110-ac33-4aeb-8d59-2b9bae3da0d3)

**Comment by LynnHaDo** [comment]
Hi!

Thank you for your interest in my project. Currently, my model is only detecting individual checkboxes and lines of boxes that are spaced out, not placed adjacently like the image you are sending. I am not 100% sure that this would work, but I can think of 2 possible suggestions (provided with some resources where you can look into more details):

1. Tabular data extraction: 

- https://paperswithcode.com/task/table-detection
- https://github.com/microsoft/table-transformer
- Or more broadly, https://github.com/topics/table-detection

2. I used to work on a project where I used the models that I created and fine-tuned it using some human-annotated images that contain adjacent boxes. The result is pretty good, but you might need to consider the robustness of the training data, when to stop training, any augmentations... to prevent overfitting. I am sorry that I cannot share those images publicly, but if you have the resources available to do that, it can be a possible solution!

Hope this helps!
